### ISSUE TITLE
Incorrect installer behavior on Linux systems

### ISSUE THREAD

**Issue by TheEmeraldKytten** [Psychon-Dev-Studios/new_winline#2]
When the user attempts to use the Installer on a Linux system, the installer should warn that it doesn't support Linux, and prompt the user to download "terminal.py" from the release page.

Instead, the installer assumes the system is running Windows and crashes

**Comment by psychon-night** [comment]
The installer is only intended to be used on Windows systems. We warn users of this problem in every release. If we ever update the installer, we might get around to fixing this issue, but we will not fix it otherwise.

Again, if you're not using Windows, please don't use the installer. Instead, just use the terminal.py file provided in each release

**Comment by psychon-night** [comment]
This issue will be resolved in version 3.8 with a dedicated Linux installer

**Comment by psychon-night** [comment]
This is resolved with newer releases. A new **installl_linux.py** file is included with newer releases, allowing correct installer behavior on Linux systems
